### ISSUE TITLE
下载歌词的问题

### ISSUE THREAD

**Issue by yuyongjie** [hzexe/Hzexe.QQMusic#1]
public async Task<bool> downloadLyricAsync(SongItem songItem, string songdir)函数
![20190107101900](https://user-images.githubusercontent.com/26709200/50745535-b178ed80-1265-11e9-8f2b-7329f7d11552.png)

**Comment by hzexe** [comment]
Fixed at https://github.com/hzexe/Hzexe.QQMusic/commit/fd9463e679db6847fdb703a84f591726c29e42ac#diff-f089e21921bf6757135247f67608f99cR139
